### PR TITLE
Control of how network BroadcastReceiver check connectivity

### PR DESCRIPTION
**Pull request by dgorohov**
Fix of issue #99. There's no possibility to switch TransferService to check if target device is connected to WiFi or Mobile network. For some cases when a big file is downloaded/uploaded it make sense to do it when device is connected to WiFi. Right now the BroadcastReceiver checks only it's connected to internet (3G or WiFi). 

I've updated following methods: `TransferUtility.download` and `TransferUtility.upload` (added Type of connectivity check). For example:
`new TransferUtility(s3client, context).download(bucketName, key, file, NetworkInfoReceiver.Type.WIFI_ONLY)`. It means the new command would we passed to TransferService, and it would switch the receiver's connectivity checker to check if device is connected to WiFi or not. Following checkers are supported in PR:
- ANY (3G or WiFi);
- MOBILE_NETWORK (3g)
- WIFI_ONLY (WiFi only)

### CODE REVIEW

**Comment by karthiksaligrama** [comment]
Can you rebase your changes over latest master, so i can pull this feature in?

**Comment by dgorohov** [comment]
@karthiksaligrama sure.

**Comment by dgorohov** [comment]
Done.

**Comment by dgorohov** [comment]
@karthiksaligrama Sorry, will do it again ...

**Comment by dgorohov** [comment]
@karthiksaligrama moved to https://github.com/aws/aws-sdk-android/pull/230

**Pull request closed without merging**
