### PR TITLE
Add the ability to enable logging.

### PR DESCRIPTION
**Pull request by yperess**
Specifically, if this configuration option is set,
the UrlHttpClient will print cURL commands that can
be replayed from command line.

### CODE REVIEW

**Comment by yperess** [comment]
Ping? This change is a blocker for my team.

**Comment by karthiksaligrama** [comment]
Can you add some test cases?

**Comment by yperess** [comment]
Sure, I'll post them ASAP.

**Comment by yperess** [comment]
Sorry for the thrashing, I can't get my local run of the unit tests to match your CI. The tests should be done soon.

**Comment by yperess** [comment]
OK, all good.

**Comment by yperess** [comment]
Ping, have you had a chance to review this?

**Comment by yperess** [comment]
Please, I'd really like to avoid this ugly build hack I'm having to pull a part of your maven repo and a part of my own module in our project.

**Comment by yperess** [comment]
Ping?

**Comment by karthiksaligrama** [comment]
Sorry for the delay in response. I'll take a look at this.

**Comment by yperess** [comment]
Pong?

**Comment by yperess** [comment]
https://www.youtube.com/watch?v=y7EpSirtf_E

**Comment by yperess** [comment]
...

**Comment by yperess** [comment]
You guys broke the CI build...

**Pull request merged**
