### PR TITLE
Fix Apache Commons Logging issue in API Level 28+  [WIP]

### PR DESCRIPTION
**Pull request by minbi**
This is a work in progress meant to be a preview. Please comment any issues you have with the approach or bugs that you find while testing.

### CODE REVIEW

**Comment by pavlospt** [comment]
It looks good to me! As I understand it you need to add the missing implementations for methods such as `trace` and afterwards it seems ready to be shipped! Please let us know if we can still help!

**Comment by pavlospt** [comment]
Apart from trace() which i am not sure how it worked before, looks good to me! I expected though, that traace would also log execution time. Might be wrong, but otherwise why would it be named trace?

**Comment by laramartin** [comment]
hey! thanks for the update, looks awesome! We can't wait for the release :) Thanks for your work!

**Comment by pavlospt** [comment]
@kvasukib @minbi Is it ready to be shipped? :)

**Comment by kvasukib** [comment]
@pavlospt There are few more changes to be done in the pull request. We are working on it.

**Comment by ygnessin** [comment]
@kvasukib @minbi any updates on this? We are waiting on it to deploy the update to our app

**Comment by pavlospt** [comment]
@kvasukib will check it in a couple of hours! Thanks for fixing it!

**Comment by kvasukib** [comment]
Closing this PR as the changes were pulled internally and released.

**Pull request closed without merging**
